name: Weekly Cloud Backup

on:
  workflow_dispatch: # Manual button
  schedule:
    - cron: '0 0 * * 0'

jobs:
  backup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true

      - name: Verify Rclone Installation
        run: rclone version 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Backup Script
        run: |
          pip install rclone-python
          python backup.py